name: Build JDK for ARM

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Build with CI build script
      run: ./ci_build.sh

    - name: Upload build output
      uses: actions/upload-artifact@v1
      with:
        name: jre
        path: jre.tar.xz
